### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by lava6ek** [1makarov/binance-nft-bot#1]
Привет, это парсер цен для бинанс маркета нфт? Было бы круто если бы ты поделился ReadMe :)

**Comment by 1makarov** [comment]
Привет, в каком-то то плане - да, это парсер. Но между тем написан на скорую руку, и не практически не подлежит дальнейшей реализации. На данный момент нет желания его переделывать, поэтому вряд ли когда-то появиться Readme.
