### ISSUE TITLE
I get "error request 0" when I run main.go

### ISSUE THREAD

**Issue by dhaern** [1makarov/binance-nft-bot#2]
Hello, I would like try this market scanner but I think Im getting errors with proxies? Are proxies needed? I hope you can check it:

"error request 0" related to line 73 in bot.go.

Can you fix this scanner and make it functional even if you dont want keep updating and adding more features? Thanks.

**Comment by 1makarov** [comment]
Hello, proxies are required, you can update and refine the application yourself
